2025-05-16 09:17:18,071 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 09:17:35,459 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112660
2025-05-16 09:17:36,028 - WARNING - URL Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112664: Status Code 403
2025-05-16 09:18:04,864 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112665: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:18:21,675 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112666: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:18:37,348 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112667: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:18:52,851 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112668: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:19:08,514 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112669: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:19:25,719 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112670: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:19:42,535 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112671: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:19:59,693 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112672: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:20:16,505 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112673: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:20:33,287 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112674: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:20:49,915 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112675: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:21:06,894 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112676: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:21:23,822 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112677: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:21:40,601 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112678: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:21:57,611 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112679: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:22:01,352 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112680
2025-05-16 09:22:07,715 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112681
2025-05-16 09:22:27,915 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112682: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:22:31,744 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112683
2025-05-16 09:22:57,334 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112684: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:23:12,846 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112685: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:23:29,624 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112686: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:23:45,175 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112687: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:23:48,815 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112688
2025-05-16 09:24:15,731 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112689: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:24:32,533 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112690: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:24:33,857 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112691
2025-05-16 09:25:00,344 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112692: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 09:25:15,878 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112693: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 09:25:17,905 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112694
2025-05-16 09:25:17,945 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6510>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:17,985 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f5dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,025 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6720>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,065 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f52b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,104 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5206909d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,145 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f5460>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,185 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7c20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,226 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6120>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,266 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f65d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,306 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6ea0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,346 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5206909d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,386 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f51f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,425 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f5940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,465 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7560>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,504 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f56a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,543 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,583 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f520690ac00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,623 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52069092b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:18,960 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 09:25:19,277 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
2025-05-16 09:25:19,316 - ERROR - Request Error http://15.235.15.230:14487/: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:19,973 - INFO - URL OK: https://cdn-3.nxplay.com.br/GLOBO_SP_TK/tracks-v1a1/mono.m3u8
2025-05-16 09:25:20,281 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 09:25:20,740 - INFO - URL OK: http://hls1.sua.tv:80/live/globosphd/s.m3u8
2025-05-16 09:25:20,956 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/90059.m3u8: Status Code 404
2025-05-16 09:25:21,086 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/91431.m3u8: Status Code 404
2025-05-16 09:25:21,275 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/90034.m3u8: Status Code 404
2025-05-16 09:25:21,413 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91421.m3u8: Status Code 404
2025-05-16 09:25:21,544 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91435.m3u8: Status Code 404
2025-05-16 09:25:21,679 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91463.m3u8: Status Code 404
2025-05-16 09:25:21,827 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/90064.m3u8: Status Code 404
2025-05-16 09:25:21,979 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/90019.m3u8: Status Code 404
2025-05-16 09:25:22,126 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95441.m3u8: Status Code 404
2025-05-16 09:25:22,262 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91405.m3u8: Status Code 404
2025-05-16 09:25:22,394 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91413.m3u8: Status Code 404
2025-05-16 09:25:22,525 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/120082.m3u8: Status Code 404
2025-05-16 09:25:22,661 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91443.m3u8: Status Code 404
2025-05-16 09:25:22,861 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91445.m3u8: Status Code 404
2025-05-16 09:25:23,013 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95483.m3u8: Status Code 404
2025-05-16 09:25:23,153 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/97396.m3u8: Status Code 404
2025-05-16 09:25:23,308 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91456.m3u8: Status Code 404
2025-05-16 09:25:23,465 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91460.m3u8: Status Code 404
2025-05-16 09:25:23,593 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/95448.m3u8: Status Code 404
2025-05-16 09:25:23,733 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91461.m3u8: Status Code 404
2025-05-16 09:25:23,876 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91467.m3u8: Status Code 404
2025-05-16 09:25:24,032 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91470.m3u8: Status Code 404
2025-05-16 09:25:24,171 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91471.m3u8: Status Code 404
2025-05-16 09:25:24,302 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91473.m3u8: Status Code 404
2025-05-16 09:25:24,449 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91477.m3u8: Status Code 404
2025-05-16 09:25:24,588 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91479.m3u8: Status Code 404
2025-05-16 09:25:24,627 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7bf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,667 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f62d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,707 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f5fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,746 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52069098b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,786 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5206909df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,825 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,865 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,904 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f65d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,944 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f54c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:24,984 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f520690a060>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,024 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f520690ac30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,063 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f7ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,102 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6420>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,142 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f69f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,182 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f75f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,221 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f520690af30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,261 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52069082f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,300 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52070f6d80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 09:25:25,817 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 09:25:26,097 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
