2025-05-16 06:23:45,528 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 06:24:00,820 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112660
2025-05-16 06:25:01,869 - INFO - URL OK: http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112664
2025-05-16 06:25:34,193 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112665: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:25:49,609 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112666: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:26:05,101 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112667: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:26:21,685 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112668: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:26:38,228 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112669: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:26:54,769 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112670: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:27:11,382 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112671: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:27:26,794 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112672: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:27:42,223 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112673: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:27:57,629 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112674: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:28:13,044 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112675: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:28:29,584 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112676: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:28:46,122 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112677: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:29:02,775 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112678: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:29:19,324 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112679: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:29:35,845 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112680: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:29:52,381 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112681: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:30:07,795 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112682: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:30:24,405 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112683: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:30:40,943 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112684: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:30:57,585 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112685: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:31:14,297 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112686: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:31:29,734 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112687: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:31:46,281 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112688: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:32:01,700 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112689: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:32:17,121 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112690: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:32:33,664 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112691: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out.
2025-05-16 06:32:49,084 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112692: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:33:04,501 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112693: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:33:19,904 - ERROR - Request Error http://callvip.me:80/DodaLiin/jXcQY5EUFzcqjn72PTRD/112694: HTTPConnectionPool(host='146.0.35.86', port=8065): Read timed out. (read timeout=15)
2025-05-16 06:33:19,924 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748d670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:19,943 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748df70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:19,963 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d02bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:19,982 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4177872ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,002 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748d850>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,021 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748eab0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,040 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748fc20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,059 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748f710>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,079 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d03380>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,099 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d02630>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,118 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748ce90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,138 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748e600>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,157 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748edb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,177 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748f4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,196 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d02d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,216 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d013a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,235 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748f440>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,254 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748c920>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:20,494 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 06:33:20,709 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
2025-05-16 06:33:20,729 - ERROR - Request Error http://15.235.15.230:14487/: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748ee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:21,234 - WARNING - URL Error https://cdn-3.nxplay.com.br/GLOBO_SP_TK/tracks-v1a1/mono.m3u8: Status Code 403
2025-05-16 06:33:21,473 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 06:33:21,707 - INFO - URL OK: http://hls1.sua.tv:80/live/globosphd/s.m3u8
2025-05-16 06:33:22,639 - INFO - URL OK: http://metv.fun:80/4x6cXF/JDqRqj/90059.m3u8
2025-05-16 06:33:23,443 - WARNING - URL Error http://metv.fun:80/4x6cXF/JDqRqj/91431.m3u8: Status Code 404
2025-05-16 06:33:24,415 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/90034.m3u8
2025-05-16 06:33:25,458 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91421.m3u8
2025-05-16 06:33:26,469 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91435.m3u8
2025-05-16 06:33:27,358 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91463.m3u8
2025-05-16 06:33:28,366 - INFO - URL OK: http://metv.fun:80/4x6cXF/JDqRqj/90064.m3u8
2025-05-16 06:33:29,429 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/90019.m3u8
2025-05-16 06:33:30,331 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95441.m3u8
2025-05-16 06:33:31,230 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91405.m3u8
2025-05-16 06:33:32,123 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91413.m3u8
2025-05-16 06:33:33,186 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/120082.m3u8
2025-05-16 06:33:34,091 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91443.m3u8
2025-05-16 06:33:35,125 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91445.m3u8
2025-05-16 06:33:36,020 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95483.m3u8
2025-05-16 06:33:37,060 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/97396.m3u8
2025-05-16 06:33:37,949 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91456.m3u8
2025-05-16 06:33:38,455 - WARNING - URL Error http://lidns.cc:80/4x6cXF/JDqRqj/91460.m3u8: Status Code 404
2025-05-16 06:33:39,365 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/95448.m3u8
2025-05-16 06:33:40,380 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91461.m3u8
2025-05-16 06:33:41,368 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91467.m3u8
2025-05-16 06:33:42,271 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91470.m3u8
2025-05-16 06:33:43,278 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91471.m3u8
2025-05-16 06:33:44,186 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91473.m3u8
2025-05-16 06:33:45,188 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91477.m3u8
2025-05-16 06:33:46,070 - INFO - URL OK: http://lidns.cc:80/4x6cXF/JDqRqj/91479.m3u8
2025-05-16 06:33:46,090 - ERROR - Request Error http://15.235.15.230:14783/: HTTPConnectionPool(host='15.235.15.230', port=14783): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748e030>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,110 - ERROR - Request Error http://15.235.15.230:14478/: HTTPConnectionPool(host='15.235.15.230', port=14478): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d02c30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,129 - ERROR - Request Error http://15.235.15.230:14492/: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417837e840>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,148 - ERROR - Request Error http://15.235.15.230:14485/: HTTPConnectionPool(host='15.235.15.230', port=14485): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748f2f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,168 - ERROR - Request Error http://15.235.15.230:14495/: HTTPConnectionPool(host='15.235.15.230', port=14495): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748d5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,187 - ERROR - Request Error http://15.235.15.230:14502/: HTTPConnectionPool(host='15.235.15.230', port=14502): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748cec0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,206 - ERROR - Request Error http://15.235.15.230:14506/: HTTPConnectionPool(host='15.235.15.230', port=14506): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748f470>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,226 - ERROR - Request Error http://15.235.15.230:14504/: HTTPConnectionPool(host='15.235.15.230', port=14504): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d01a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,245 - ERROR - Request Error http://15.235.15.230:14508/: HTTPConnectionPool(host='15.235.15.230', port=14508): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d03d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,265 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748ed80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,284 - ERROR - Request Error http://15.235.15.230:14512/: HTTPConnectionPool(host='15.235.15.230', port=14512): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748d3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,304 - ERROR - Request Error http://15.235.15.230:14510/: HTTPConnectionPool(host='15.235.15.230', port=14510): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748c7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,323 - ERROR - Request Error http://15.235.15.230:14516/: HTTPConnectionPool(host='15.235.15.230', port=14516): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748e330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,343 - ERROR - Request Error http://15.235.15.230:14492/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14492): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d03080>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,362 - ERROR - Request Error http://15.235.15.230:14487/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14487): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4176d036b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,381 - ERROR - Request Error http://15.235.15.230:14499/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14499): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748ecc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,401 - ERROR - Request Error http://15.235.15.230:14513/AFDTV: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: /AFDTV (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748cfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,420 - ERROR - Request Error http://15.235.15.230:14513/: HTTPConnectionPool(host='15.235.15.230', port=14513): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f417748ef00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-16 06:33:46,652 - INFO - URL OK: http://hls1.sua.tv/live/globotvbahiafhdbr2/s.m3u8
2025-05-16 06:33:46,866 - WARNING - URL Error http://s1.1-cup.net:2095/solucao111hgfgh77hu78/xplus1111XXhjgyu87/51: Status Code 404
